// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/UserInfoPb.proto

package com.lihao.netty.protobuf;

public interface UserInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.UserInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string userName = 1;</code>
   */
  java.lang.String getUserName();
  /**
   * <code>string userName = 1;</code>
   */
  com.google.protobuf.ByteString
      getUserNameBytes();

  /**
   * <code>string address = 2;</code>
   */
  java.lang.String getAddress();
  /**
   * <code>string address = 2;</code>
   */
  com.google.protobuf.ByteString
      getAddressBytes();

  /**
   * <code>string desc = 3;</code>
   */
  java.lang.String getDesc();
  /**
   * <code>string desc = 3;</code>
   */
  com.google.protobuf.ByteString
      getDescBytes();

  /**
   * <code>int32 userId = 4;</code>
   */
  int getUserId();
}
